apiVersion: v1
kind: Service
metadata:
  # The required headless service for StatefulSets
  name: openhack/minecraft-server
  labels:
    app: minecraft-server
spec:
  ports:
  - port: 25575
    name: default
  - port: 25565
    name: RCON
  clusterIP: None
  selector:
    app: minecraft-server
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-cluster
  labels:
    app: minecraft-server
spec:
  ports:
  - port: 25575
    name: default
  - port: 25565
    name: rcon
  type: LoadBalancer
  selector:
    app: minecraft-server
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minecraft-server
spec:
  serviceName: "minecraft-server"
  replicas: 4
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: minecraft-server
        image: openhack/minecraft-server
        ports:
        - containerPort: 25575
          name: default
        - containerPort: 25565
          name: rcon
        volumeMounts:
        - name: minecraft
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: minecraft
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi # make this bigger in production
