apiVersion: v1
kind: Service
metadata:
  name: minecraftrconapi
  labels:
    app: minecraftrconapi
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    run: minecraftrconapi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minecraftrconapi
  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: minecraftrconapi
        app: minecraftrconapi
    spec:
      containers:
        - name: minecraft
          image: 'shanepeckham/minecraftrconapi'
          env:
            - name: EULA
              value: 'TRUE'
            - name: NAMESPACE
              value: "default"
          ports:
            - containerPort: 8080
---
