apiVersion: v1
kind: Service
metadata:
  # The required headless service for StatefulSets
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  ports:
  - port: 25575
    name: default
  - port: 25565
    name: rcon
  clusterIP: None
  selector:
    app: minecraft-server-t18
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-cluster-1
  labels:
    app: minecraft-server-t18
spec:
  ports:
  - port: 25575
    name: default
  - port: 25565
    name: rcon
  type: LoadBalancer
  selector:
    app: minecraft-server-t18
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-cluster-2
  labels:
    app: minecraft-server-t18
spec:
  ports:
  - port: 25575
    name: default
  - port: 25565
    name: rcon
  type: LoadBalancer
  selector:
    app: minecraft-server-t18
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-cluster-3
  labels:
    app: minecraft-server-t18
spec:
  ports:
  - port: 25575
    name: default
  - port: 25565
    name: rcon
  type: LoadBalancer
  selector:
    app: minecraft-server-t18
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minecraft-server-t18
spec:
  serviceName: "minecraft-server-t18"
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft-server-t18
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: minecraft-server-t18
        image: openhack/minecraft-server:2.0
        env:
        - name: EULA
          value: "TRUE"
        - name: MAX_PLAYERS
          value: "100"
        - name: MOTD
          value: "OpenHack is really cool in Amsterdam !"
        - name: ALLOW_FLIGHT
          value: "TRUE"
        - name: WORLD
          value: "/data/world"
        ports:
        - containerPort: 25575
          name: default
        - containerPort: 25565
          name: rcon
        volumeMounts:
        - name: mc-persistent-storage-world
          mountPath: /data/world
      volumes:
      - name: mc-persistent-storage-world
        azureFile:
          secretName: azure-fs-secret
          shareName: team18mc-world
          readOnly: false