apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app: minecraft
  namespace: minecraft
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: ui
    - port: 25575
      targetPort: 25575
      protocol: TCP
      name: rcon
  selector:
    run: minecraft
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: minecraftvolume
  namespace: minecraft
spec:
  storageClassName: managed-standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: minecraft
        app: minecraft
        namespace: minecraft
    spec:
      containers:
        - name: minecraft
          image: 'openhack/minecraft-server:1.0'
          env:
            - name: EULA
              value: 'TRUE'
          ports:
            - containerPort: 25565
              name: ui
            - containerPort: 25575
              name: rcon
          volumeMounts:
          - mountPath: /data
            name: minecraftvolume
      volumes:
      - name: minecraftvolume
        persistentVolumeClaim:
          claimName: minecraftpvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraftpvc
  namespace: minecraft
  annotations: 
    volume.beta.kubernetes.io/storage-class: managed-standard
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
