apiVersion: v1
kind: Secret
metadata:
  name: omsagent-secret
type: Opaque
data:
  WSID: dae1ce35-0fc3-49c9-9dad-cfb5c17108ba
  KEY: uXxWP9RbttsQvjpFB82udzPJDkztT8Ljju5z5zLeBsFJ40tjQ0sQGS3hTEGyeM+vOcpzpl/KMMzsFwZQShaG4g==
