apiVersion: v1
kind: Secret
metadata:
  name: azure-fs-secret
type: Opaque
data:
  azurestorageaccountname: MDB3NDdvcWZyemE2ZjY2YWdudDA=
  azurestorageaccountkey: eUVMT2JDQlU5ZE5DVTQvTjMrVmVySjVQM2Jjcjg1R1BiMkwvMnVWU3dwVGpIWWxMYjE2T3IxNER4Zm9KQWhjS2ZKVzJ1Qkp5dmJPcXc3ZGswRzlCZ2c9PQ==